apiVersion: v1 # api version used to create Pod objects
kind: Pod # object type we want to create
metadata:
  name: datascientest-pod # Pod name
spec:
  containers:
    - name: nginx # container to create for Pod
      image: nginx # image to be used to create container
      imagePullPolicy: IfNotPresent # only if not present, download image
      volumeMounts:
        - name: datascientest-volume
          mountPath: /usr/share/nginx/html/ # directory in container to be mounted on volume
      ports:
        - containerPort: 80 # container listening port
  volumes:
    - name: datascientest-volume # volume name for persistent data storage
      persistentVolumeClaim:
        claimName: pvc-datascientest # PVC name used
