apiVersion: v1
data:
  mysql-password: ZGF0YXNjaWVudGVzdDEyMzQ=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: user-api-dev
    meta.helm.sh/release-namespace: dev
  creationTimestamp: "2025-07-08T19:47:22Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: user-api-dev-datascientest-chart-db
  namespace: dev
  resourceVersion: "50916"
  uid: 007e0e0c-1fe8-421e-b5ed-ccff809ae322
type: Opaque
